server:
  port: 8082

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION:36000000}

rabbitmq:
  messaging:
    exchange: auth.exchange
    otp-queue: notification.auth.otp.requested.queue
    wallet-queue: wallet.auth.user.created.queue
    routing-key-otp: auth.otp.requested
    routing-key-wallet: auth.user.created
    rollback-queue: auth.user.rollback.queue
    audit-exchange: audit.exchange
    audit-queue: audit.log.created.queue
    audit-routing-key: audit.log.created

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/wallet_auth}
    username: ${CORE_DB_USER}
    password: ${CORE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis-server}
      port: ${SPRING_REDIS_PORT:6379}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq-server}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${RMQ_USER:guest}
    password: ${RMQ_PASSWORD:guest}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true