server:
  port: 8010

spring:
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq-server}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}

rabbitmq:
  messaging:
    queue: notification.auth.otp.requested.queue

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://discovery-service:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
